name: testing playwright

on:
  pull_request:
    branches: [ main, master ]

jobs:
  test_browserstack:
    runs-on: ubuntu-latest
    environment: browserstack
    name: Playwright
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'npm'

      - name: Install Dependencies
        run: npm i

      - name: Build Highcharts
        run: npx gulp scripts

      - name: Checkout utils
        uses: actions/checkout@v4
        with:
          repository: highcharts/highcharts-utils
          path: utils
          fetch-depth: 1

      - name: Install Highcharts Utils
        run: |
          cd utils
          npm i

      - name: 'BrowserStack Env Setup'
        uses: 'browserstack/github-actions/setup-env@master'
        with:
          username:  ${{ secrets.BROWSERSTACK_USER }}
          access-key: ${{ secrets.BROWSERSTACK_KEY }}

      - name: 'BrowserStackLocal Setup'
        uses: 'browserstack/github-actions/setup-local@master'
        with:
          local-testing: start
          local-args: '--proxy-server=127.0.0.1 --proxy-port=3030'

      - name: Run Playwright tests
        env: 
          BROWSERSTACK_KEY: ${{ secrets.BROWSERSTACK_KEY }}
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
        run: |
          npx browserstack-node-sdk playwright test

          - name: 'Stop BrowserStackLocal'
        uses: 'browserstack/github-actions/setup-local@master'
        with:
          local-testing: 'stop'
